//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class accommodation
    {
        public string quote_no { get; set; }
        public string order_no { get; set; }
        public string accomname { get; set; }
        public string checkin { get; set; }
        public string checkout { get; set; }
        public string numberofpeople { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual order order { get; set; }
    }
}
