//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class accommodation
    {
        public string quote_no { get; set; }
        public string order_no { get; set; }
        public string accomname { get; set; }
        public string accom_id { get; set; }
        public Nullable<System.DateTime> checkin { get; set; }
        public Nullable<System.DateTime> checkout { get; set; }
        public Nullable<int> numberofguests { get; set; }
        public Nullable<int> numberofrooms { get; set; }
        public Nullable<double> amount { get; set; }
        public string accomspecs { get; set; }
    }
}
