//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class agencydetail
    {
        public string agency_id { get; set; }
        public string nameofagency { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public string emailaddress { get; set; }
        public string fax { get; set; }
        public string cellphone { get; set; }
        public string service { get; set; }

        //TODO - acgeny_id generation function
    }
}
