//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cabservice
    {
        public string nameofagency { get; set; }
        public string quote_no { get; set; }
        public string nameofdriver { get; set; }
        public string pickup { get; set; }
        public string dropoff { get; set; }
        public Nullable<System.DateTime> dateofcab { get; set; }
        public string phonenumber { get; set; }
    
        public virtual quote quote { get; set; }
    }
}
