//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class carhire
    {
        public string quote_no { get; set; }
        public string order_no { get; set; }
        public string agencyname { get; set; }
        public string pickuplocation { get; set; }
        public string dropofflocation { get; set; }
        public Nullable<System.DateTime> dayofhire { get; set; }
        public Nullable<System.DateTime> expectedenddate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string carhirespecifications { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> numberofcars { get; set; }
        public Nullable<System.DateTime> startday { get; set; }
    }
}
