//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.orders = new HashSet<order>();
        }
    
        public string client_no { get; set; }
        public string quote_no { get; set; }
        public string clientname { get; set; }
        public string phonenumber { get; set; }
        public string address { get; set; }
        public string emailaddress { get; set; }
        public Nullable<decimal> paid { get; set; }
        public Nullable<decimal> owe { get; set; }
        public Nullable<decimal> amountcarried { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
