//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class conference
    {
        public string venue { get; set; }
        public string conferencename { get; set; }
        public string timeconference { get; set; }
        public string quote_no { get; set; }
    
        public virtual quote quote { get; set; }
    }
}
