//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dailyserviceupdate
    {
        public System.DateTime datestamp { get; set; }
        public string servicename { get; set; }
        public string client_no { get; set; }
        public string clientname { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> frequency { get; set; }
    }
}
