//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public string quote_no { get; set; }
        public string order_no { get; set; }
        public string eventspecs { get; set; }
        public string eventname { get; set; }
        public Nullable<double> amount { get; set; }

        public @event(string name, string specs, double amount)
        {
            eventname = name;
            eventspecs = specs;
            this.amount = amount;
        }
    }
}
