//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public string event_id { get; set; }
        public string nameofevent { get; set; }
        public string resourcesneeded { get; set; }
        public string eventlocation { get; set; }
    }
}
