//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public string invoice_no { get; set; }
        public string order_no { get; set; }
        public Nullable<System.DateTime> invoicedate { get; set; }
        public string clientname { get; set; }
        public Nullable<double> paymentduration { get; set; }
        public Nullable<double> owe { get; set; }
        public Nullable<double> paid { get; set; }
    
        public virtual order order { get; set; }
    }
}
