//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public string order_no { get; set; }
        public string quote_no { get; set; }
        public string client_no { get; set; }
        public Nullable<System.DateTime> datereceived { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
    }
}
