//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
   
    public partial class quote
    {
        public string quote_no { get; set; }
        public Nullable<double> amount { get; set; }
        public string service { get; set; }
        public string timequoted { get; set; }
        public string timesent { get; set; }
        public Nullable<System.DateTime> datesent { get; set; }
        public Nullable<System.DateTime> quotedate { get; set; }
        public string consultant_no { get; set; }
        public Nullable<double> servicefee { get; set; }
        public string client_no { get; set; }
        public string clientname { get; set; }

        public static int totalQuotes = 0;

        public quote(double amount, string typeOfServices, string consultant_no,string client_no,string clientname,double serviceFee)
        {
            this.amount = amount;
            service = typeOfServices;
            this.consultant_no = consultant_no;
            this.clientname = clientname;
            this.client_no = client_no;
            this.servicefee = serviceFee;
            quotedate = DateTime.Now;
        }
        /// <summary>
        /// It generates a new quote number
        /// </summary>
        private void makeQuote_no()
        {
            quotedate = DateTime.Now; // Assignes the timeQuoted to the current time
            string _totalQts = totalQuotes.ToString(); // assigns the static value to the string
            while (_totalQts.Length < 6)
            {
                // It adds a zero once to the left of the current string
                _totalQts = _totalQts.PadLeft(1, '0');
            }
            // generates the quote number using the time and string generated above
            quote_no = $"{quotedate}{_totalQts}";
        }

        public override string ToString()
        {
            return base.ToString();

        }
    }
}
