//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class quote
    {
        public string quote_no { get; set; }
        public Nullable<double> amount { get; set; }
        public string service { get; set; }
        public string timequoted { get; set; }
        public string timesent { get; set; }
        public Nullable<System.DateTime> datesent { get; set; }
        public Nullable<System.DateTime> quotedate { get; set; }
        public string consultant_no { get; set; }
        public string agencyphonenumber { get; set; }
        public Nullable<double> servicefee { get; set; }
        public string agencyname { get; set; }
        public string client_no { get; set; }
        public string clientname { get; set; }
    }
}
