//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public string staff_id { get; set; }
        public string stafffirstnames { get; set; }
        public string stafflastname { get; set; }
        public string staffposition { get; set; }
        public Nullable<System.DateTime> dateofhire { get; set; }
        public Nullable<double> salary { get; set; }
        public string branch { get; set; }
    }
}
