//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher
    {
        public string voucher_no { get; set; }
        public string order_no { get; set; }
        public string client_id { get; set; }
        public string accomm_id { get; set; }
        public string agency_id { get; set; }
        public string staff_id { get; set; }
        public Nullable<double> amount { get; set; }
    }
}
