//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleleTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher
    {
        public string voucher_no { get; set; }
        public string order_no { get; set; }
        public string client_id { get; set; }
        public string accomm_id { get; set; }
        public string agency_id { get; set; }
        public string staff_id { get; set; }
        public Nullable<double> amount { get; set; }

        voucher(order _order, client Client, accommodation Accom, agencydetail Agency, staff Staff, double amount)
        {
            order_no = _order.order_no;
            client_id = Client.client_no;
            accomm_id = Accom.accom_id;
            agency_id = Agency.agency_id;
            staff_id = Staff.staff_id;
        }
    }
}
